package uk.gov.digital.ho.pttg.application;

public enum LogEvent {
    HMRC_ACCESS_CODE_SERVICE_STARTED,
    HMRC_GET_ACCESS_CODE_SUCCESS,
    HMRC_PROXY_ENABLED,
    HMRC_ACCESS_CODE_REFRESH_REQUESTED,
    HMRC_ACCESS_CODE_REPORTED,
    HMRC_ACCESS_CODE_REFRESHED,
    HMRC_ACCESS_CODE_REFRESH_FAILURE,
    HMRC_ACCESS_CODE_AUTHENTICATION_ERROR,
    HMRC_ACCESS_CODE_RESPONSE_SUCCESS,
    HMRC_ACCESS_CODE_RESPONSE_ERROR,
    HMRC_ACCESS_CODE_REQUESTED,
    HMRC_PROXY_ERROR,
    HMRC_TOTP_GENERATOR_ERROR,
    HMRC_ACCESS_CODE_REFRESH_RESPONSE_SUCCESS,
    HMRC_ACCESS_CODE_REPORTED_RESPONSE_SUCCESS,
    HMRC_ACCESS_CODE_AUDIT_FAILURE;

    public static final String EVENT = "event_id";
}